### ISSUE TITLE
Torch Error

### ISSUE THREAD

**Issue by r0f1** [GT-RIPL/L2C#4]
Hi, running `python demo.py` gives me the following error. any idea on how to fix that?

```
==== Epoch:0 ====
/projects/anaconda3/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:82: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
LR: 0.001
Itr            |Batch time     |Data Time      |Loss
Traceback (most recent call last):
  File "demo.py", line 295, in <module>
    run(get_args(sys.argv[1:]))
  File "demo.py", line 236, in run
    train(epoch, train_loader, learner, args)
  File "demo.py", line 76, in train
    confusion.add(output, eval_target)
  File "/projects/unsupervised/05_test_l2c/L2C/utils/metric.py", line 69, in add
    output = output.squeeze_()
RuntimeError: set_storage_offset is not allowed on a Tensor created from .data or .detach().
If your intent is to change the metadata of a Tensor (such as sizes / strides / storage / storage_offset)
without autograd tracking the change, remove the .data / .detach() call and wrap the change in a `with torch.no_grad():` block.
For example, change:
    x.data.set_(y)
to:
    with torch.no_grad():
        x.set_(y)
```
```
> pip freeze | grep torch
torch==1.2.0
torchvision==0.4.0a0+6b959ee
```

**Comment by yenchanghsu** [comment]
Hi, this repo currently only supports PyTorch version 1.0.1.post2. We might update the repo to support a newer version of PyTorch in the future.

**Comment by r0f1** [comment]
Ok thanks for the clarification!

**Comment by yenchanghsu** [comment]
I made a small change (https://github.com/GT-RIPL/L2C/commit/068dba574f81e5e95216d304764ee5c7a433e4fa) to allow the repo runs with both PyTorch 1.3.1 and 1.0.1. However, for an unknown reason, Version 1.3.1 leads to a lower performance (2~3 points lower) compared to 1.0.1, when running the demo_omniglot_transfer.py. Please let me know if anyone has an idea of how this happened. Thanks!
